apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ai2gjcffn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ai2gjcffn-go 
  name: ai2gjcffn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ai2gjcffn-go 
